In [ ]:
import numpy as np
import time

#vector is a numpy  1-D array.

#vector addition
a=np.array([1,5,13])
b=np.array([2,4,61])
print(" vector addition : {a+b}")
print(a+b)



 vector addition : {a+b}
[ 3  9 74]


In [ ]:
#single vector operations
print("mean")
print(np.mean(a))

print("\n -ve")
d=-a
print(d)

print("\n sum of vector")
print(np.sum(a))

print("\n square of the vector ")
e=a**2
print(e)


mean
6.333333333333333

 -ve
[ -1  -5 -13]

 sum of vector
19

 square
[  1  25 169]


In [ ]:
def dot(f,g):
  x=0
  for i in range(a.shape[0]): ## non-vector fn
    x=x+a[i]*b[i]
  return x

  f=np.array([1,5,6])
g=np.array([2,7,9])
print(dot(f,g))

815


In [ ]:
k=np.array([3,67]) #vectorized form of dot product. it processes much faster than non-vectorized version
l=np.array([2,6])
t=np.dot(k,l)
print(t)

408
